name: Build and Publish

on:
  push:
    branches: ["main"]

jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Enviroment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: "NPM Identity"
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc    
      - name: Setup Packages
        run: yarn
      - name: Generate CSS
        run: yarn build-css
      - name: Deploy to NPM Registory
        run: yarn deploy
