name: Build and Publish

on:
  push:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Enviroment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: "NPM Identity"
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc    
      - name: Setup Packages
        run: yarn
      - name: Generate CSS
        run: yarn build-css
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
  Publish:  
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Approval
        uses: trstringer/manual-approval@v1.8.0
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: handakina
          minimum-approvals: 1
      - name: Deploy to NPM Registory
        run: yarn deploy
